# Generated by Django 3.2.4 on 2021-06-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sdescription', models.TextField()),
                ('ldescription', models.TextField()),
                ('technology', models.CharField(max_length=30)),
                ('image', models.FilePathField(path='/img')),
                ('second_img', models.FilePathField(path='/img')),
                ('link', models.URLField()),
            ],
        ),
    ]
